#!/bin/sh

LOGFILE="/tmp/TcpDump2Mqtt.log"

log() {
    # Print to stdout and append to log file with timestamp
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOGFILE"
}

function kill_childs() {
	PID="$(ps -edf | grep sh | grep StartMqttSend | awk '{print $2}')"
	if [ -n "${PID}" ]; then
		kill $PID > /dev/null
		log "Killed StartMqttSend process with PID $PID"
	fi

	PID="$(ps -edf | grep mosquitto_pub | grep $TOPIC_DUMP | awk '{print $2}')"
	if [ -n "${PID}" ]; then
		kill $PID > /dev/null
		log "Killed mosquitto_pub process with PID $PID"
	fi

	PID="$(ps -edf | grep python | grep filter.py | awk '{print $2}')"
	if [ -n "${PID}" ]; then
		kill $PID > /dev/null
		log "Killed filter.py process with PID $PID"
	fi

	PID="$(ps -edf | grep tcpdump | grep 30006 | awk '{print $2}')"
	if [ -n "${PID}" ]; then
		kill $PID > /dev/null
		log "Killed tcpdump process with PID $PID"
	fi

	PID="$(ps -edf | grep sh | grep StartMqttReceive | awk '{print $2}')"
	if [ -n "${PID}" ]; then
		kill $PID > /dev/null
		log "Killed StartMqttReceive process with PID $PID"
	fi

	PID="$(ps -edf | grep mosquitto_sub | grep $TOPIC_RX | awk '{print $2}')"
	if [ -n "${PID}" ]; then
		kill $PID > /dev/null
		log "Killed stale mosquitto_sub process with PID $PID"
	fi

        PID="$(ps -edf | grep binnendeurbel | awk '{print $2}')"
        if [ -n "${PID}" ]; then
                kill $PID > /dev/null
                log "killed binnendeurbel"
        fi

}

function exit_handler() {
	log "Goodbye cruel world! x____x"
	kill_childs
	exit $?
}

trap exit_handler SIGINT SIGTERM

CFGFILE=/etc/tcpdump2mqtt/TcpDump2Mqtt.conf

# Check config file
if ! ([ -f $CFGFILE ] && [ -s $CFGFILE ]); then
	log "Configuration file missing or empty!"
	exit 1
fi

# Import configs
set -a
. $CFGFILE
set +a

# Check config params
if ([ -z "${MQTT_HOST}" ] || [ -z "${MQTT_PORT}" ] || ([ -n "${MQTT_USER}" ] && [ -z "${MQTT_PASS}" ]) || \
    [ -z "${TOPIC_RX}" ] || [ -z "${TOPIC_DUMP}" ] || [ -z "${TOPIC_STARTD}" ] || [ -z "${TOPIC_LASTWILL}" ] || \
	([ -n "${MQTT_CAFILE}" ] && [ -z "${MQTT_CERTFILE}" ] && [ -z "${MQTT_KEYFILE}" ])); then
	log "Wrong configuration, please check config file!"
	exit 1
fi

# Display configuration
LOG_MSG="MQTT host $MQTT_HOST"

if [ -n "${MQTT_USER}" ]; then
	LOG_MSG="$LOG_MSG | MQTT authentication user and password enabled"
elif [ -n "${MQTT_CAFILE}" ]; then
	LOG_MSG="$LOG_MSG | MQTT authentication using certificate enabled"
fi
log "$LOG_MSG"

# Kill any previous stale process
log "Checking for stale processes..."
kill_childs

log "Starting watchdog loop"

# Main watchdog loop
while :
	do
		# Update gateway address dynamically in case network connects after script starts
		GWADDR="$(route -n | awk '$1 == "0.0.0.0" || $4 == "UG" {print $2}' | head -n 1)"
		# If gateway is still empty, fallback to MQTT_HOST to test connection
		if [ -z "$GWADDR" ]; then
			GWADDR="$MQTT_HOST"
		fi

		PING=`ping -s 1 -c 4 ${GWADDR} > /dev/null; echo $?`
		FILE=/tmp/flexisip_restarted

		if [ $PING -ne 0 ] || [ -f "$FILE" ]; then
			# Network is down or flexisip restarted

			if [ -f "$FILE" ]; then
				/bin/rm "$FILE"
				log "Removed Flexisip restarted file"
			fi
            
			if [ $PING -ne 0 ]; then
				log "Network is down (Ping to $GWADDR failed)"
			fi

			kill_childs
		else
			# Network is up

                        # if binnendeurbel process is not running, start it
                        if ! /usr/bin/pgrep -x binnendeurbel > /dev/null ; then
                                log "Starting binnendeurbel process..."
                                /etc/tcpdump2mqtt/binnendeurbel &
                                log "binnendeurbel process started"
                        fi

			# If MQTT sender is not running, start it
			if ! /usr/bin/pgrep -x tcpdump > /dev/null ; then
				log "Starting MQTT sender..."
				/etc/tcpdump2mqtt/StartMqttSend &
				log "MQTT sender started"
				/bin/sleep 5

				log "Publishing start date message..."
				if [ -n "${MQTT_USER}" ]; then
					/bin/date +"%Y-%m-%dT%H:%M:%S" | /usr/bin/mosquitto_pub -l -r -h ${MQTT_HOST} -p ${MQTT_PORT} -u ${MQTT_USER} -P ${MQTT_PASS} -t ${TOPIC_STARTD}
				elif [ -n "${MQTT_CAFILE}" ]; then
					/bin/date +"%Y-%m-%dT%H:%M:%S" | /usr/bin/mosquitto_pub -l -r -h ${MQTT_HOST} -p ${MQTT_PORT} -t ${TOPIC_STARTD} --cafile ${MQTT_CAFILE} --cert ${MQTT_CERTFILE} --key ${MQTT_KEYFILE}
				else
					/bin/date +"%Y-%m-%dT%H:%M:%S" | /usr/bin/mosquitto_pub -l -r -h ${MQTT_HOST} -p ${MQTT_PORT} -t ${TOPIC_STARTD}
				fi
			fi

			# If MQTT receiver is not running, start it
			if ! /usr/bin/pgrep -x mosquitto_sub > /dev/null ; then
				log "Starting MQTT receiver..."
				/etc/tcpdump2mqtt/StartMqttReceive &
				log "MQTT receiver started"
				/bin/sleep 5

				log "Publishing online status message..."
				if [ -n "${MQTT_USER}" ]; then
					/usr/bin/mosquitto_pub -r -h ${MQTT_HOST} -p ${MQTT_PORT} -u ${MQTT_USER} -P ${MQTT_PASS} -t ${TOPIC_LASTWILL} -m online
				elif [ -n "${MQTT_CAFILE}" ]; then
					/usr/bin/mosquitto_pub -r -h ${MQTT_HOST} -p ${MQTT_PORT} -t ${TOPIC_LASTWILL} -m online --cafile ${MQTT_CAFILE} --cert ${MQTT_CERTFILE} --key ${MQTT_KEYFILE}
				else
					/usr/bin/mosquitto_pub -r -h ${MQTT_HOST} -p ${MQTT_PORT} -t ${TOPIC_LASTWILL} -m online
				fi
			fi
		fi

		/bin/sleep 1m
	done
